### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [astei/lazydfu#12] opened 2021-06-24 22:54 UTC
First screenshot is with Lazydfu installed
Second screenshot is without Lazydfu installed
I walked around in new chunks in the same world in both screenshots

![Lazydfu installed](https://user-images.githubusercontent.com/86382621/123342164-dab09580-d514-11eb-9ad5-490d663d617a.png)
![Lazydfu not installed](https://user-images.githubusercontent.com/86382621/123342171-e13f0d00-d514-11eb-9df2-2801d79739c5.png)

**Comment by astei** [comment] 2021-06-25 12:51
This can be expected if you loaded a world that needs to be migrated from an older version of the game - I recommend using the "Optimize World" feature to eliminate any spikes LazyDFU might cause.

However, these are the least of your problems. Your problem is going to require some additional mods like [Lithium](https://modrinth.com/mod/lithium) and [Sodium](https://modrinth.com/mod/sodium) to solve.

Closing this issue is there really isn't a issue at all, LazyDFU is working as intended.

**Closed by astei** 2021-06-25 12:51 UTC
